version: '3.8'

services:
  todo:
    build: ./
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=pass
    networks:
      - app

  db:
    restart: always
    container_name: mysql_db
    image: mysql:8
#    command: ./init.sql
    environment:
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=todo
    volumes:
      - ./.database/mysql/data:/var/lib/mysql
    ports:
      - "33060:3306"
    hostname: "todo"
    networks:
      - app

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database", "mysql://todo:pass@tcp(db:33060)/todo", "up"]
    networks:
      - app
    volumes:
      - .:/migrations
    links:
      - db
    depends_on:
      - db

networks:
  app:
    driver: "bridge"